[package]
name = "embedded-svc"
version = "0.16.2"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "hal"]
description = "A set of traits for services higher level than embedded-hal and typically found in embedded microcontrollers with WiFi or BLE support."
repository = "https://github.com/esp-rs/embedded-svc"
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
default = ["std", "use_serde", "use_strum", "use_numenum"]

# Uncomment once 0.6.2 which has no_std support is released
#experimental = ["domain"]
experimental = []

std = ["alloc", "anyhow/std", "serde/std", "serde_json/std", "strum/std", "num_enum/std", "url", "http-auth-basic"]
alloc = ["anyhow", "serde/alloc", "serde_json/alloc"]
use_serde = ["enumset/serde", "no-std-net/serde"]
use_strum = ["strum", "strum_macros"]
use_numenum = ["num_enum"]

[dependencies]
log = { version = "0.4", default-features = false }
async-trait = "0.1"
no-std-net = { version = "0.5", default-features = false }
enumset = { version = "1", default-features = false }
anyhow = { version = "1", default-features = false, optional = true }
strum = { version = "0.23", default-features = false, optional = true, features = ["derive"] }
strum_macros = { version = "0.23", optional = true }
num_enum = { version = "0.5", default-features = false, optional = true }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, optional = true }
url = { version = "2", optional = true }
http-auth-basic = { version = "0.1", optional = true }
# Uncomment once 0.6.2 which has no_std support is released
#domain = { version = "0.6", optional = true, default-features = false }
